<?php 
// $LastChangedBy: slavik $ $Rev: 208 $ $LastChangedDate: 2013-04-10 18:46:18 +0600 (Ср, 10 апр 2013) $
// $Id: makep12.php 208 2013-04-10 12:46:18Z slavik $
$zippath="/tmp/ssl";
if (!file_exists($zippath)) die("ERROR: temp directory not exist $zippath");
if (!is_writable($zippath)) die("ERROR: temp directory read only $zippath");


if (isset($_POST['element_1'])) { 
$p12k="";
	$cert=$_POST['element_1'];
	$key=$_POST['element_2'];
	$pass=$_POST['element_3'];
	if (FALSE==$pkey=openssl_pkey_get_private($key)) die('failed to open key\n $key');
	if (FALSE==$x509=openssl_x509_read($cert)) die('failed to open cert\n $cert');
	$cert_info=print_r(openssl_x509_parse($x509), TRUE);
	if (FALSE==openssl_pkcs12_export($x509,$p12k,$pkey,$pass)) {

while (($e = openssl_error_string()) !== false) {
    echo $e . "\n";
}
die("\nfailed to make p12, probably you supplied cert from another key?\n $cert_info");};
	$zip = new ZipArchive();
	$filename = "$zippath/p12_".time().".zip";
	
	if ($zip->open($filename, ZIPARCHIVE::CREATE)!==TRUE) {
		die("cant open <$filename>\n");
	}
	
	$zip->addFromString("certinfo.txt", "$cert_info\n");
	$zip->addFromString("password.txt", "$pass\n");
	$zip->addFromString("cert.pem", "$cert\n");
	$zip->addFromString("key.pem", "$key\n");
	$zip->addFromString("cert.p12", "$p12k\n");
	$zip->close();	
	
	
	$simple = "cert_p12_".time().".zip";
	header('Content-Disposition: attachment; filename='.$simple);
	readfile($filename);
	die(0);
};

function passGen()
{
	$chars="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyz";
	$minchars=15;
	$maxchars=20;

	$escapecharplus=0;
	$repeat=mt_rand($minchars,$maxchars);

	while ($escapecharplus<$repeat)
	{
		$randomword.=$chars[mt_rand(1, strlen($chars)-1)];
		$escapecharplus+=1;
	}
	return $randomword;
};
$pass=passGen();
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
<html xmlns=\"http://www.w3.org/1999/xhtml\">
<head>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">
<title>sslmanager: make p12</title>
<link rel=\"stylesheet\" type=\"text/css\" href=\"view.css\" media=\"all\">
<script type=\"text/javascript\" src=\"view.js\"></script>

</head>
<body id=\"main_body\" >
	
	<img id=\"top\" src=\"top.png\" alt=\"\">
	<div id=\"form_container\">
	
		<h1><a>create p12</a></h1>
		<form id=\"form_574014\" class=\"appnitro\"  method=\"post\" action=\"\">
					<div class=\"form_description\">
			<h2>create p12</h2>
			<p>please paste certificate and private key</p>
		</div>						
			<ul >
			
					<li id=\"li_1\" >
		<label class=\"description\" for=\"element_1\">CERTIFICATE</label>
		<div>
			<textarea id=\"element_1\" name=\"element_1\" class=\"element textarea large\"></textarea> 
		</div><p class=\"guidelines\" id=\"guide_1\"><small>certificate begin from line -----BEGIN CERTIFICATE----- till line -----END CERTIFICATE-----
 you should paste block with both these lines</small></p> 
		</li>		<li id=\"li_2\" >
		<label class=\"description\" for=\"element_2\">RSA PRIVATE KEY </label>
		<div>
			<textarea id=\"element_2\" name=\"element_2\" class=\"element textarea large\"></textarea> 
		</div><p class=\"guidelines\" id=\"guide_2\"><small>private key begin from line -----BEGIN RSA PRIVATE KEY----- till line -----END RSA PRIVATE KEY-----
you should paste block with both these lines</small></p> 
		</li>
			<li id=\"li_3\" >
		<label class=\"description\" for=\"element_3\">password</label>
		<div>
			<input id=\"element_3\" name=\"element_3\" class=\"element text large\" type=\"text\" maxlength=\"255\" value=\"$pass\"/> 
		</div><p class=\"guidelines\" id=\"guide_3\"><small>this is autogenerated password, i will save it in zip file</small></p> 
		</li>
					
					<li class=\"buttons\">
			    <input type=\"hidden\" name=\"form_id\" value=\"574014\" />
			    
				<input id=\"saveForm\" class=\"button_text\" type=\"submit\" name=\"submit\" value=\"make p12\" />
		</li>
			</ul>
		</form>	
		<div id=\"footer\">
			Generated by <a href=\"http://www.phpform.org\">pForm</a>
		</div>
	</div>
	<img id=\"bottom\" src=\"bottom.png\" alt=\"\">
	</body>
</html>";

?>